/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ApiLinksDocument.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

import {AmfHelperMixin} from '@api-components/amf-helper-mixin/amf-helper-mixin.js';

export {ApiLinksDocument};

declare class ApiLinksDocument {
  readonly styles: any;
  render(): any;
  _linkTemplate(link: any): any;
  _linkOperationTemplate(link: any): any;
  _mappingsTemplate(link: any): any;
  _mappingTemplate(mapping: any): any;
}
